# Generated by Django 4.2.6 on 2023-11-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Передача')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Передача',
                'verbose_name_plural': 'Передачи',
            },
        ),
        migrations.AlterModelOptions(
            name='chanells',
            options={'ordering': ['-published'], 'verbose_name': 'Телеканал', 'verbose_name_plural': 'Телеканалы'},
        ),
        migrations.AlterField(
            model_name='chanells',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='chanells',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='chanells',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='chanells',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Телеканал'),
        ),
    ]
