# Generated by Django 4.2.6 on 2023-11-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0002_tvshows_alter_chanells_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='chanell',
            field=models.TextField(blank=True, null=True, verbose_name='Канал трансляции'),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='timeend',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='timestart',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='Тип передачи'),
        ),
    ]
