# Generated by Django 4.2.6 on 2023-11-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0003_tvshows_chanell_tvshows_timeend_tvshows_timestart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название типа передачи')),
                ('content', models.IntegerField(blank=True, null=True, verbose_name='Возрастной ценз')),
            ],
            options={
                'verbose_name': 'Тип передач',
                'verbose_name_plural': 'Типы передач',
            },
        ),
        migrations.AlterModelOptions(
            name='chanells',
            options={'verbose_name': 'Телеканал', 'verbose_name_plural': 'Телеканалы'},
        ),
        migrations.RemoveField(
            model_name='chanells',
            name='price',
        ),
        migrations.RemoveField(
            model_name='chanells',
            name='published',
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название передачи'),
        ),
    ]
