# Generated by Django 4.2.6 on 2023-11-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0004_type_alter_chanells_options_remove_chanells_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanells',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
